markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - images
  - styles
plugins:
  - jekyll-assets
  - jekyll-minifier

assets:
  compression: true
  source_maps: false
  defaults:
    js:
      integrity: true
    css:
      integrity: true
    img:
      integrity: false
  sources:
    - images
    - styles

jekyll-minifier:
  remove_intertag_spaces: true
